---
development:
  cloud_name: aggie-rotaract
  api_key: <%= ENV["cloud_key"] %>
  api_secret: <%= ENV["cloud_secret"] %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: aggie-rotaract
  api_key: <%= ENV["cloud_key"] %>
  api_secret: <%= ENV["cloud_secret"] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: aggie-rotaract
  api_key: <%= ENV["cloud_key"] %>
  api_secret: <%= ENV["cloud_secret"] %>
  enhance_image_tag: true
  static_image_support: false
